# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 9889
    start_block: 0
    contracts:
      - name: Diesel
        address:
          - 0x7c293b054938bedca41354203be4c08aec2c3466412cac803f4ad62abf22e476
        abi_file_path: abis/mainnet/diesel-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: MintEvent
          - name: BurnEvent
          - name: CreatePoolEvent
          - name: SwapEvent
raw_events: true
