# yaml-language-server: $schema=./node_modules/envio/fuel.schema.json
name: envio-indexer
ecosystem: fuel
networks:
  - id: 0
    start_block: 0
    hyperfuel_config:
      url: https://mainnet2.hypersync.xyz
    contracts:
      - name: Diesel
        address:
          - 0x7c293b054938bedca41354203be4c08aec2c3466412cac803f4ad62abf22e476
        abi_file_path: abis/mainnet/diesel-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: MintEvent
          - name: BurnEvent
          - name: CreatePoolEvent
          - name: SwapEvent
          - name: TotalSupplyEvent
      - name: BridgeFungibleToken
        address:
          - 0x4ea6ccef1215d9479f1024dff70fc055ca538215d2c8c348beddffd54583d0e8
        abi_file_path: abis/mainnet/bridgefungibletoken-abi.json
        handler: src/EventHandlers.ts
        events:
          - name: ClaimRefundEvent
            logId: "4873341570055982168"
          - name: BridgeFungibleTokenError
            logId: "797431737660767716"
          - name: RefundRegisteredEvent
            logId: "5994656859013025846"
          - name: WithdrawalEvent
            logId: "5416159340904421156"
          - name: SetMetadataEvent
            logId: "17415926155927968170"
          - name: SetSymbolEvent
            logId: "12152039456660331088"
          - name: ReentrancyError
            logId: "5557842539076482339"
          - name: SetDecimalsEvent
            logId: "18149631459970394923"
          - name: TotalSupplyEvent
            logId: "17462098202904023478"
          - name: DepositEvent
            logId: "12590297951544646752"
          - name: SetNameEvent
            logId: "7845998088195677205"
raw_events: true
